version: '3'
services:
  mobilenet_v1:
    image: triage/model-serving
    ports:
      - "9001:9000"
    environment:
      MODEL_URL: https://s3.amazonaws.com/tf-models-839c7ddd-9cab-49fa-9b42-bde1a842086e/mobilenet_v1.tar.gz
  inception_v3:
    image: triage/model-serving
    ports:
      - "9002:9000"
    environment:
      MODEL_URL: https://s3.amazonaws.com/tf-models-839c7ddd-9cab-49fa-9b42-bde1a842086e/inception_v3.tar.gz
  xception:
    image: triage/model-serving
    ports:
      - "9003:9000"
    environment:
      MODEL_URL: https://s3.amazonaws.com/tf-models-839c7ddd-9cab-49fa-9b42-bde1a842086e/xception.tar.gz
  resnet50:
    image: triage/model-serving
    ports:
      - "9004:9000"
    environment:
      MODEL_URL: https://s3.amazonaws.com/tf-models-839c7ddd-9cab-49fa-9b42-bde1a842086e/resnet50.tar.gz
  vgg16:
    image: triage/model-serving
    ports:
      - "9005:9000"
    environment:
      MODEL_URL: https://s3.amazonaws.com/tf-models-839c7ddd-9cab-49fa-9b42-bde1a842086e/vgg16.tar.gz
  vgg19:
    image: triage/model-serving
    ports:
      - "9006:9000"
    environment:
      MODEL_URL: https://s3.amazonaws.com/tf-models-839c7ddd-9cab-49fa-9b42-bde1a842086e/vgg19.tar.gz
